'use strict';
const $=s=>document.querySelector(s), KEY='yeoun.archive.v1';
let records=[],editing=null,selected=null,demo=false;
const samples=[['서이현',2025,'여름의 잔상'],['윤서하',2025,'여름의 잔상'],['백도윤',2025,'서로의 궤도'],['한유진',2025,'서로의 궤도'],['차은재',2024,'푸른 시간'],['강태오',2024,'푸른 시간'],['문하린',2023,'이름 없는 계절'],['정시온',2023,'이름 없는 계절']].map((a,i)=>({id:'sample-'+i,name:a[0],year:a[1],community:a[2],image:'assets/portrait-'+(i+1)+'.svg',note:'디자인을 살펴보기 위한 가상 캐릭터입니다. 실제 캐릭터의 사진과 이야기로 바꿔 주세요.'}));
function restoreSampleLayout(previous){try{if(localStorage.getItem('yeoun.layout.restore.v1'))return previous;const restored=[...previous,...samples.filter(sample=>!previous.some(row=>row.id===sample.id))];localStorage.setItem(KEY,JSON.stringify(restored));localStorage.setItem('yeoun.layout.restore.v1','1');return restored}catch{return previous}}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('visible'),3500)}
function validImage(s){return isAllowedImage(s)}
function validate(data){if(!Array.isArray(data)||data.length>300)throw Error('자료는 최대 300개의 캐릭터 목록이어야 합니다.');const ids=new Set();return data.map(r=>{if(!r||typeof r.name!=='string'||!r.name.trim()||r.name.length>80||typeof r.community!=='string'||!r.community.trim()||r.community.length>120||!Number.isInteger(r.year)||r.year<1900||r.year>2100||!validImage(r.image)||r.image.length>2500000||typeof r.note!=='string'||r.note.length>2000||(r.altName!==undefined&&(typeof r.altName!=='string'||r.altName.length>120)))throw Error('캐릭터 자료 형식 또는 이미지가 올바르지 않습니다.');const id=typeof r.id==='string'&&r.id.length<100?r.id:crypto.randomUUID();if(ids.has(id))throw Error('중복된 캐릭터 ID가 있습니다.');ids.add(id);return{id,name:r.name.trim(),year:r.year,community:r.community.trim(),image:r.image,note:r.note,altName:(r.altName||'').trim()}})}
function persist(next){try{localStorage.setItem(KEY,JSON.stringify(next));records=next;demo=records.some(r=>r.id.startsWith('sample-'));render();return true}catch{toast('저장 공간이 부족하거나 브라우저 저장이 차단되었습니다. 자료를 내보내 백업하세요.');return false}}
function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n}
function render(){const archive=$('#archive'),nav=$('#years');archive.replaceChildren();nav.replaceChildren();const years=[...new Set(records.map(r=>r.year))].sort((a,b)=>b-a);$('#total').textContent=String(records.length).padStart(2,'0')+' '+siteCopy.characterLabel+' / '+years.length+' '+siteCopy.seasonLabel;years.forEach(year=>{const group=records.filter(r=>r.year===year);const a=el('a','',String(year));a.href='#year-'+year;nav.append(a);const section=el('section','year-section');section.id='year-'+year;const heading=el('div','year-heading'),title=el('div','year-title');title.append(el('h2','',String(year)),el('span','',String(group.length).padStart(2,'0')+' '+siteCopy.characterLabel));heading.append(title);section.append(heading);const grid=el('div','grid');group.forEach((r,i)=>{const card=el('button','card');card.setAttribute('aria-label',r.name+' · '+r.community+' · '+year+'년 상세 보기');const portrait=el('div','portrait');portrait.dataset.viewStory=siteCopy.viewStory;const img=el('img');img.src=r.image;img.alt=r.name+'의 초상';img.loading='lazy';portrait.append(img);const meta=el('div','card-meta');meta.append(el('span','card-name',r.name),el('span','card-num',String(i+1).padStart(2,'0')));card.append(portrait,meta);if(r.altName)card.append(el('div','card-alt-name',r.altName));card.append(el('div','card-community',r.community));card.onclick=()=>showDetail(r.id);grid.append(card)});section.append(grid);const caption=el('div','year-caption');caption.append(el('span','',''),el('span','',String(year)));section.append(caption);archive.append(section)});if(!years.length)archive.append(el('p','empty','아직 남겨진 얼굴이 없습니다. 아카이브 관리에서 첫 캐릭터를 등록하세요.'));renderManager();observer?.disconnect();observer=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting)nav.querySelectorAll('a').forEach(a=>a.classList.toggle('active',a.hash==='#'+e.target.id))},{rootMargin:'-10% 0px -60% 0px'});document.querySelectorAll('.year-section').forEach(s=>observer.observe(s));applyCopy()}
let observer;
function showDetail(id){const r=records.find(r=>r.id===id);selected=id;$('#detail-image').src=r.image;$('#detail-image').alt=r.name;$('#detail-name').textContent=r.name;$('#detail-alt-name').textContent=r.altName||'';$('#detail-alt-name').hidden=!r.altName;$('#detail-year').textContent=r.year+' / CHARACTER ARCHIVE';$('#detail-community').textContent=r.community;$('#detail-note').textContent=r.note;$('#detail').showModal()}
function renderManager(){const list=$('#manage-list');list.replaceChildren();[...records].sort((a,b)=>b.year-a.year).forEach(r=>{const row=el('div','manage-row'),img=el('img');img.src=r.image;img.alt='';const text=el('span','',r.name+' · '+r.community);text.append(el('br'),el('small','',String(r.year)));const button=el('button','text-button','수정 ↗');button.onclick=()=>openEditor(r.id);row.append(img,text,button);list.append(row)})}
function openEditor(id=null){editing=id;const r=records.find(r=>r.id===id),f=$('#character-form');f.reset();$('#editor-title').textContent=r?'캐릭터 수정':'캐릭터 등록';$('#delete').hidden=!r;f.elements.name.value=r?.name||'';f.elements.altName.value=r?.altName||'';f.elements.imageUrl.value=isHttpsImageUrl(r?.image)?r.image:'';f.elements.year.value=r?.year||new Date().getFullYear();f.elements.community.value=r?.community||'';f.elements.note.value=r?.note||'';$('#editor').showModal()}
async function imageData(file){if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>5*1024*1024)throw Error('5MB 이하의 PNG, JPG, WebP 이미지를 선택해 주세요.');const bitmap=await createImageBitmap(file);const scale=Math.min(1,1000/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();return canvas.toDataURL('image/webp',.85)}
$('#character-form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,save=f.querySelector('[type=submit]');save.disabled=true;setMacBusy(true);try{const old=records.find(r=>r.id===editing),file=f.elements.photo.files[0],imageUrl=f.elements.imageUrl.value.trim();if(!file&&imageUrl&&!isHttpsImageUrl(imageUrl))throw Error('https://로 시작하는 직접 이미지 주소를 입력해 주세요.');if(!old&&!file&&!imageUrl)throw Error('이미지 파일 또는 이미지 링크를 입력해 주세요.');const r={id:editing||crypto.randomUUID(),name:f.elements.name.value.trim(),altName:f.elements.altName.value.trim(),year:Number(f.elements.year.value),community:f.elements.community.value.trim(),note:f.elements.note.value,image:file?await imageData(file):(imageUrl||old?.image)};validate([r]);const next=editing?records.map(x=>x.id===editing?r:x):[...records,r];if(persist(next)){$('#editor').close();toast('캐릭터를 저장했습니다.')}}catch(err){toast(err.message)}finally{save.disabled=false;setMacBusy(false)}};
$('#delete').onclick=()=>{if(confirm('이 캐릭터를 삭제할까요? 백업이 없으면 되돌릴 수 없습니다.')&&persist(records.filter(r=>r.id!==editing))){$('#editor').close();toast('캐릭터를 삭제했습니다.')}};
$('#manage').onclick=()=>$('#manager').showModal();$('#add').onclick=()=>openEditor();$('#edit-selected').onclick=()=>{$('#detail').close();$('#manager').showModal();openEditor(selected)};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}}));
$('#export').onclick=()=>{const blob=new Blob([JSON.stringify(records,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download='archive.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('자료를 내보냈습니다. 안전한 곳에 보관하세요.')};
$('#import').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>20*1024*1024)throw Error('가져오기 파일은 20MB 이하여야 합니다.');const next=validate(JSON.parse(await file.text()));if(confirm('현재 목록을 가져온 자료로 교체할까요? 먼저 내보내기로 백업하는 것을 권합니다.'))if(persist(next))toast('자료를 가져왔습니다.')}catch(err){toast(err.message)}finally{e.target.value=''}};

async function init(){try{const saved=localStorage.getItem(KEY);if(saved!==null){records=restoreSampleLayout(validate(JSON.parse(saved)));demo=records.some(r=>r.id.startsWith('sample-'));render();return}}catch{toast('저장된 자료를 읽지 못했습니다. 백업 파일을 가져와 주세요.')}try{localStorage.setItem('yeoun.layout.restore.v1','1')}catch{}try{const response=await fetch('archive.json');if(response.ok){records=validate(await response.json());demo=records.some(r=>r.id.startsWith('sample-'));render();return}}catch{}records=samples;demo=true;render()}


const COPY_FIELDS={"titleLead": {"label": "큰 제목 앞부분", "value": "얼굴의"}, "titleAccent": {"label": "큰 제목 뒷부분", "value": "기록."}, "subtitle": {"label": "큰 제목 아래 영문", "value": "ONE NAN"}, "spine": {"label": "왼쪽 세로 제목", "value": "Character archive"}, "characterLabel": {"label": "캐릭터 수 단위", "value": "CHARACTERS"}, "seasonLabel": {"label": "연도 수 단위", "value": "SEASONS"}, "viewStory": {"label": "사진 hover 문구", "value": "더보기"}, "managerTitle": {"label": "관리 화면 제목", "value": "이야기를 모으는 곳."}, "footerHandle": {"label": "푸터 문구", "value": "@ererwintaft"}}, COPY_KEY='yeoun.copy.v1';
const defaultCopy=Object.fromEntries(Object.entries(COPY_FIELDS).map(([k,v])=>[k,v.value]));
let siteCopy={...defaultCopy},publishedCopy={...defaultCopy},copyEditing=false,copyBefore=null;
function validateCopy(data){if(!data||typeof data!=='object'||Array.isArray(data))throw Error('문구 파일 형식이 올바르지 않습니다.');const result={};for(const key of Object.keys(defaultCopy)){const value=data[key]??defaultCopy[key];if(typeof value!=='string'||value.length>600)throw Error('각 문구는 600자 이내의 텍스트여야 합니다.');result[key]=value}result.spine=result.spine.replace(/\s*[—–-]\s*\d+\s*\/\s*∞\s*$/,'');result.spine=result.spine.charAt(0).toUpperCase()+result.spine.slice(1).toLowerCase();if(result.subtitle.trim()==='THE CHARACTER FILES')result.subtitle='ONE NAN';return result}
function copyNode(tag,cls,key){const node=el(tag,cls,siteCopy[key]);node.dataset.copy=key;return node}
function applyCopy(){document.querySelectorAll('[data-copy]').forEach(n=>{const key=n.dataset.copy;if(key in siteCopy)n.textContent=siteCopy[key];n.contentEditable=copyEditing?'plaintext-only':'false';n.classList.toggle('copy-editable',copyEditing);if(copyEditing)n.setAttribute('aria-label',COPY_FIELDS[key].label+' 편집');else n.removeAttribute('aria-label')});$('#spine-count').textContent=' — '+String(records.length).padStart(2,'0')+' / ∞';document.title=[siteCopy.titleLead,siteCopy.titleAccent].filter(Boolean).join(' ')||'Character Archive';$('#copy-toolbar').hidden=!copyEditing;document.body.classList.toggle('copy-editing',copyEditing)}
async function loadCopy(){try{const r=await fetch('settings.json',{cache:'no-store'});if(r.ok)publishedCopy=validateCopy(await r.json())}catch{}siteCopy={...publishedCopy};try{const local=localStorage.getItem(COPY_KEY);if(local!==null)siteCopy=validateCopy(JSON.parse(local))}catch{toast('문구를 읽지 못했습니다. 백업 파일을 가져와 주세요.')}if(/^VIEW STORY/i.test(siteCopy.viewStory))siteCopy.viewStory='더보기';render()}
function startCopy(){if(copyEditing)return;copyBefore={...siteCopy};copyEditing=true;applyCopy();toast('점선 글자를 눌러 수정하세요. 모든 문구에서 작은 라벨도 수정할 수 있어요.')}
function collectInline(){document.querySelectorAll('[data-copy]').forEach(n=>{const key=n.dataset.copy;if(key in siteCopy)siteCopy[key]=n.innerText.replace(/\u00a0/g,' ')})}
function stopCopy(){copyEditing=false;copyBefore=null;render()}
$('#edit-copy').onclick=()=>{if(copyEditing)$('#copy-toolbar').scrollIntoView({block:'nearest'});else startCopy()};
$('#copy-save').onclick=()=>{try{collectInline();siteCopy=validateCopy(siteCopy);localStorage.setItem(COPY_KEY,JSON.stringify(siteCopy));stopCopy();toast('문구를 저장했습니다. 공개하려면 상단의 공개 사이트에 게시를 눌러 주세요.')}catch(e){toast(e.name==='QuotaExceededError'?'브라우저 저장 공간이 부족합니다.':e.message)}};
$('#copy-cancel').onclick=()=>{siteCopy={...copyBefore};stopCopy()};
function openCopyFields(){collectInline();const list=$('#copy-fields-list');list.replaceChildren();for(const [key,meta] of Object.entries(COPY_FIELDS)){const label=el('label','',meta.label),input=el('textarea');input.name=key;input.maxLength=600;input.rows=key==='description'?3:1;input.value=siteCopy[key];label.append(input);list.append(label)}$('#copy-dialog').showModal()}
$('#copy-fields').onclick=openCopyFields;
$('#copy-form').onsubmit=e=>{e.preventDefault();const form=e.currentTarget;try{const next={};for(const key of Object.keys(defaultCopy))next[key]=form.elements.namedItem(key).value;siteCopy=validateCopy(next);$('#copy-dialog').close();render()}catch(err){toast(err.message)}};
function downloadCopy(){if(copyEditing)collectInline();try{const data=validateCopy(siteCopy),url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=el('a');a.href=url;a.download='settings.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('문구 백업을 내보냈습니다. 공개는 상단의 게시 버튼을 사용하세요.')}catch(e){toast(e.message)}}
$('#copy-export').onclick=downloadCopy;
$('#copy-import').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>50000)throw Error('문구 파일은 50KB 이하여야 합니다.');const next=validateCopy(JSON.parse(await file.text()));siteCopy=next;$('#copy-dialog').close();render();toast('가져온 문구를 미리보기에 적용했습니다. 저장을 눌러 유지하세요.')}catch(err){toast(err.message)}finally{e.target.value=''}};
$('#copy-reset').onclick=()=>{if(confirm('현재 편집 중인 문구를 공개 사이트의 기본 문구로 되돌릴까요?')){siteCopy={...publishedCopy};$('#copy-dialog').close();render()}};
document.addEventListener('input',e=>{const n=e.target.closest('[data-copy]');if(n&&copyEditing){siteCopy[n.dataset.copy]=n.innerText;document.querySelectorAll('[data-copy]').forEach(other=>{if(other!==n&&other.dataset.copy===n.dataset.copy)other.textContent=n.innerText})}});
document.addEventListener('click',e=>{if(copyEditing&&e.target.closest('[data-copy]'))e.preventDefault()});
document.addEventListener('paste',e=>{const n=e.target.closest('[data-copy]');if(!copyEditing||!n)return;e.preventDefault();const selection=window.getSelection();if(!selection.rangeCount)return;const range=selection.getRangeAt(0);if(!n.contains(range.commonAncestorContainer))return;const text=e.clipboardData.getData('text/plain').slice(0,600);range.deleteContents();const node=document.createTextNode(text);range.insertNode(node);range.setStartAfter(node);range.collapse(true);selection.removeAllRanges();selection.addRange(range);siteCopy[n.dataset.copy]=n.textContent});
Promise.all([loadCopy(),init()]);

