// Open-source macOS cursor assets; immediate tracking without a trailing effect.
const macCursor=$('#cursor'),macCursorImage=macCursor.querySelector('img');
const macAssetPaths={arrow:'assets/cursors/left_ptr.svg',hand:'assets/cursors/hand2.svg',text:'assets/cursors/xterm.svg',wait:Array.from({length:40},(_,i)=>'assets/cursors/wait/wait-'+String(i+1).padStart(2,'0')+'.svg')};
const macAssets=typeof BUNDLED_CURSORS==='undefined'?macAssetPaths:BUNDLED_CURSORS;
const finePointer=matchMedia('(pointer:fine)'),reducedMotion=matchMedia('(prefers-reduced-motion:reduce)');
let macX=0,macY=0,macSeen=false,macState='arrow',macBusy=false,macFrame=0,macTimer=null,macRaf=null,macTarget=null,shakeUntil=0,shakeDirection=0,shakeTurns=0,shakeStart=0,lastMacX=0;
const macCursorScale=1.5;
const macHotspots={arrow:[10,5],hand:[11,7],text:[16,17],wait:[16,16]};
function drawMacCursor(){macRaf=null;if(!finePointer.matches||!macSeen){macCursor.style.visibility='hidden';document.documentElement.classList.remove('mac-cursor-active');document.querySelectorAll('dialog').forEach(d=>d.classList.remove('mac-cursor-active'));return}const host=macTarget?.closest('dialog[open]')||document.body;if(macCursor.parentNode!==host)host.append(macCursor);const state=macBusy?'wait':macState,hot=macHotspots[state].map(value=>value*macCursorScale);const source=state==='wait'?macAssets.wait[macFrame]:macAssets[state];if(macCursorImage.getAttribute('src')!==source)macCursorImage.src=source;macCursor.style.setProperty('--hot-x',hot[0]+'px');macCursor.style.setProperty('--hot-y',hot[1]+'px');macCursor.style.transform='translate3d('+(macX-hot[0])+'px,'+(macY-hot[1])+'px,0)';macCursor.style.visibility='visible';macCursor.dataset.state=state;macCursor.classList.toggle('shaken',performance.now()<shakeUntil&&!reducedMotion.matches);document.documentElement.classList.add('mac-cursor-active');document.querySelectorAll('dialog').forEach(d=>d.classList.toggle('mac-cursor-active',d===host))}
function requestMacDraw(){if(macRaf===null)macRaf=requestAnimationFrame(drawMacCursor)}
function setMacBusy(value){macBusy=value;if(macTimer){clearInterval(macTimer);macTimer=null}macFrame=0;if(value&&!reducedMotion.matches)macTimer=setInterval(()=>{macFrame=(macFrame+1)%macAssets.wait.length;requestMacDraw()},40);requestMacDraw()}
document.addEventListener('pointermove',e=>{if(e.pointerType==='touch'||!finePointer.matches)return;macSeen=true;macX=e.clientX;macY=e.clientY;macTarget=e.target;macState=e.target.closest('input,textarea,[contenteditable=plaintext-only]')?'text':e.target.closest('button,a,.button')?'hand':'arrow';const now=performance.now(),delta=macX-lastMacX;if(now-shakeStart>500){shakeStart=now;shakeTurns=0}if(Math.abs(delta)>12){const direction=Math.sign(delta);if(shakeDirection&&direction!==shakeDirection)shakeTurns++;shakeDirection=direction;if(shakeTurns>=4){shakeUntil=now+700;shakeTurns=0;setTimeout(requestMacDraw,720)}}lastMacX=macX;requestMacDraw()},{passive:true});
document.addEventListener('pointerout',e=>{if(!e.relatedTarget){macSeen=false;requestMacDraw()}});window.addEventListener('blur',()=>{macSeen=false;requestMacDraw()});document.querySelectorAll('dialog').forEach(d=>d.addEventListener('close',()=>{if(macCursor.parentNode===d)document.body.append(macCursor);macSeen=false;requestMacDraw()}));finePointer.addEventListener('change',requestMacDraw);
